use_frameworks!

target 'UIDynamicView_Example' do
  pod 'UIDynamicView', :path => '../'
  pod 'OsTools'
  pod 'youtube-ios-player-helper', '~> 0.1.4'
  pod 'OsUIViews'
  
  target 'UIDynamicView_Tests' do
    inherit! :search_paths

    
  end
end
